<?php
$title = 'Add Parents';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
	$form->setAttribute('action', $this->url('parents',array('action' => 'add')));
	$form->setAttribute('class', 'form-horizontal');
	
	echo $this->Form($this->form);
?>

<button onclick="return add_child()">Add a new category</button>
<button onclick="return add_hobby()">Add a new hobby</button>

<script>
    function add_child() {
        var currentCount = $('form > fieldset > fieldset > fieldset').length;
        var template = $('form > fieldset > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset > fieldset').append(template);

        return false;
    }
    function add_hobby() {
        var currentCount = $('form > fieldset > fieldset > fieldset > fieldset > fieldset').length;
        var template = $('form > fieldset > fieldset > fieldset > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset > fieldset > fieldset > fieldset').append(template);

        return false;
    }
</script>

