<?php
$title = 'Parents';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('parents', array('action'=>'add'));?>">Add new Parents</a></p>
<table class="table table-bordered table-hover">
    <tr>
        <th>Name</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($posts as $post) : ?>
	    <tr>
	        <td><?php echo $this->escapeHtml($post->getName());?></td>
	        <td>
	            <a href="<?php echo $this->url('parents', array('action' => 'edit', 'id' => $post->getId())); ?>">Edit</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url('parents', array('action' => 'delete', 'id' => $post->getId())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	    </tr>
    <?php endforeach; ?>
</table>